import 'package:dartz/dartz.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as sup;
import '../../../../core/error/failures.dart';
import '../../domain/entities/ticket_entity.dart';
import '../../domain/entities/comment_entity.dart';
import '../../domain/entities/ticket_activity_entity.dart';
import '../../domain/repositories/ticket_repository.dart';
import '../datasources/ticket_remote_data_source.dart';
import '../models/ticket_model.dart';
import '../models/comment_model.dart';

import '../../../auth/domain/entities/user_entity.dart';
import '../../../auth/data/models/user_model.dart';
import '../../../../core/constants/enums.dart';

class TicketRepositoryImpl implements TicketRepository {
  final TicketRemoteDataSource remoteDataSource;

  TicketRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Either<Failure, List<TicketEntity>>> getTickets({
    required int page,
    required int limit,
  }) async {
    try {
      final tickets = await remoteDataSource.getTickets(page, limit);
      return Right(tickets.map((t) => t.toEntity()).toList());
    } on sup.AuthException catch (e) {
      return Left(ServerFailure(message: e.message, code: 401));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<TicketEntity>>> getAllTickets({
    required int page,
    required int limit,
    String? status,
  }) async {
    try {
      final tickets = await remoteDataSource.getAllTickets(page, limit, status: status);
      return Right(tickets.map((t) => t.toEntity()).toList());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<AuthUser>>> getStaffUsers() async {
    try {
      final staffData = await remoteDataSource.getStaffUsers();
      final users = staffData.map((json) => UserModel.fromJson(json).toEntity()).toList();
      return Right(users);
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, TicketEntity>> createTicket({
    required String title,
    required String description,
    required String category,
    required String priority,
    required List<String> imagePaths,
  }) async {
    try {
      final ticketModel = TicketModel(
        id: '', // Generated by Supabase
        title: title,
        description: description,
        status: TicketStatus.open,
        priority: TicketPriority.fromString(priority),
        category: category,
        createdAt: DateTime.now(),
        userId: '', // Set by DataSource based on current auth
      );

      final createdTicket = await remoteDataSource.createTicket(ticketModel, imagePaths);
      return Right(createdTicket.toEntity());
    } on sup.AuthException catch (e) {
      return Left(ServerFailure(message: e.message, code: 401));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, TicketEntity>> getTicketDetail(String ticketId) async {
    try {
      final ticket = await remoteDataSource.getTicketDetail(ticketId);
      return Right(ticket.toEntity());
    } on sup.AuthException catch (e) {
      return Left(ServerFailure(message: e.message, code: 401));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<CommentEntity>>> getTicketComments(String ticketId) async {
    try {
      final comments = await remoteDataSource.getTicketComments(ticketId);
      return Right(comments.map((c) => c.toEntity()).toList());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, CommentEntity>> addComment({
    required String ticketId,
    required String message,
  }) async {
    try {
      final commentModel = CommentModel(
        id: '',
        ticketId: ticketId,
        userId: '', // Set by DB/DataSource
        userName: '',
        userRole: '',
        message: message,
        createdAt: DateTime.now(),
      );

      final createdComment = await remoteDataSource.addComment(commentModel);
      return Right(createdComment.toEntity());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, TicketEntity>> updateTicketStatus({
    required String ticketId,
    required TicketStatus status,
  }) async {
    try {
      final ticket = await remoteDataSource.updateTicketStatus(ticketId, status.name);
      return Right(ticket.toEntity());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<TicketActivityEntity>>> getTicketActivities(String ticketId) async {
    try {
      final activities = await remoteDataSource.getTicketActivities(ticketId);
      return Right(activities.map((a) => a.toEntity()).toList());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<TicketActivityEntity>>> getAllActivities() async {
    try {
      final activities = await remoteDataSource.getAllActivities();
      return Right(activities.map((a) => a.toEntity()).toList());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, TicketEntity>> assignTicket({
    required String ticketId,
    required String technicianId,
  }) async {
    try {
      final ticket = await remoteDataSource.assignTicket(ticketId, technicianId);
      return Right(ticket.toEntity());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }
}
